### ISSUE TITLE
Shorten the Flow Control Slot Weir

### ISSUE THREAD

**Issue by eak24** [AguaClara/aide_template-DEPRECATED#1]
Monroe:
I saw that the La Concordia plant has the tall slotted weir for backwash flow control. That weir doesn't have to be nearly so tall. We need to fix this in our designs! 
The top of the backwash flow control slotted weir just needs to be something like 5 cm taller than the upstream filtration flow distribution weir.

**Comment by MattCimini** [comment]
The downstream weir is now correctly a few cm higher than the front upstream one.
![image](https://user-images.githubusercontent.com/35536127/40252542-aa793684-5aaa-11e8-88b9-7b905e5d41de.png)
