### ISSUE TITLE
Solidify connecting geometry plan

### ISSUE THREAD

**Issue by eak24** [AguaClara/aide_template-DEPRECATED#13]
@MattCimini I think we need to solidify the connecting geometry plan. aide_design and I are looking at this as well.

I've been looking through the filter designs. There's a lot of great work happening there! I realize the entrance piping is very confusing. I'm wondering how to make it as maintainable as possible. I saw this list of parameters for a single pipe:

<img width="1268" alt="screen shot 2018-03-12 at 22 37 39" src="https://user-images.githubusercontent.com/8585379/37320119-9be9487a-2648-11e8-850f-25f5ae8249ae.png">

I wonder how useful it is to have all these parameters defined within a pipe model. This was admittedly an early strategy that I was using with the distributed design - passing all the variables from the larger context into the smaller design. I think it makes for a confusing and difficult to maintain design in the long run. 

Perhaps instead we could aim to define exactly what is relevant to the design in the context of the specific component that is being worked on. For example, it never makes sense for a straight pipe to have more than exactly three parameters: SDR, length and OD. The work the team has done on the spreadsheet that is used to calculate what length should be delivered to Fusion would then be put into the aide_template yaml templates. I'm scared of relying so heavily on Fusion's parametrization system... I find some of the conventions they exist on and the lack of inter-connectivity very frustrating. 

I think we need to get you the draw tool @AguaClara/aide_draw as soon as possible so the team can see what it is like to work within the YAML -> aide_draw -> Fusion system. 

@MattCimini I've set up weekly meetings with aide_template at 2 on Thursdays. Maybe we can discuss this more there...

**Comment by MattCimini** [comment]
Yeah I definitely acknowledge that opening the parameter list for these files can be a bit overwhelming. I wish there was a better way to transfer the data of the external context to the component without literally typing it in. 
I think Draw will be a big part of that.
I would be happy to talk Thursday (3/22) at 2:00 if you would like.

**Comment by eak24** [comment]
@MattCimini Yes - after looking at this some more, it's pretty convincing that that role should be in the hands of draw. I can do 2:30-3:30 (and I updated the google calendar). I'll pull @matanp and @prevosis into the meeting. Maybe we can ask a few of the template people to come? Which teams are at this time?

**Comment by MattCimini** [comment]
@ethan92429 2:30-3:30 is bit of an awkward time because the first group ends at 2:40 and then the second group starts at 2:55. I will be able to stay the entire time because I attend both.

**Comment by MattCimini** [comment]
The end plan is to put  double underscores ,"__" next to all parameters that are simply used for reference purposes. In this way the components don't have to be cluttered up with all the excess variables that design already knows. These reference parameters will eventually be removed from Fusion and all of the equations maed by Template will be moved into Design's YAML files
