### ISSUE TITLE
Flocculator baffles are offset and doubled

### ISSUE THREAD

**Issue by zoemaisel** [AguaClara/aide_template-DEPRECATED#18]
When I open the Fusion file for flocculator, it appears that baffles are intersecting the wall and are not using the third support. Also, the first channel appears to have double baffles. 

![image](https://user-images.githubusercontent.com/31140352/39444413-a7a3b1a6-4c85-11e8-9c0d-88107a01d397.png)

**Comment by connorli852** [comment]
Fixed by jointing the baffles to the supports
