### ISSUE TITLE
naming convention of flocculator variables

### ISSUE THREAD

**Issue by fletchapin** [AguaClara/aide_template-DEPRECATED#19]
Some of the flocculator variables have names with colons in them, such as ```Channel1:2```. This naming convention is illegal Python syntax, and we want to convert them to dictionaries so that we can access the variables so we'd like a more Python friendly name, e.g. ```Channel1_2```.

**Comment by fletchapin** [comment]
@MattCimini after talking to Ethan he told me that the colon is the default for Fusion when copies of the same object are created. He's going to try to figure out how to change this to an underscore

**Comment by MattCimini** [comment]
Not an issue
