### ISSUE TITLE
Entrance Channels of Sed Tank

### ISSUE THREAD

**Issue by MattCimini** [AguaClara/aide_template-DEPRECATED#9]
Finish the entrance channels that connect the flocculator and sedimentation tank
- decide between one long piece or multiple small pieces

**Comment by MattCimini** [comment]
Decided to pattern multiple channel pieces. 
Used a axis along these pieces to create the pattern.
These multiple smaller pieces joint smoothly.

**Comment by MattCimini** [comment]
@GabriellePeralta the next time you work on this can you look into the fact that all the holes for the inlet pipe seem to shift the farther you move down. AKA the patterned pieces of the entrance channel are too long
![image](https://user-images.githubusercontent.com/35536127/37559438-9e553f9e-29fc-11e8-80da-5216d1c2776d.png)

**Comment by GabriellePeralta** [comment]
Yes! Thanks for reminding me

**Comment by MattCimini** [comment]
We worked out the bugs. Should work fine now

**Comment by GabriellePeralta** [comment]
@MattCimini Thanks! Also, sorry I forgot to make clear, I realized my problem was cause of the way I included stuff in the file, so my correct channel stuff is in a different file, "SedTank_Channels_Gabby"
